### ISSUE TITLE
SUGGESTION: Re-add Necromorph Help

### ISSUE THREAD

**Issue by Cartlord** [DS-13-Dev-Team/DS13-2.0#220]
## Feature description
Give every Necromorph a menu they can open that explains their role & abilities in detail, including what the hotkeys for abilities (if those ever get added) and the Necro's health & weaknesses.

## Why is this feature needed/good for the game?
Makes it more friendly to newbies, since not everyone who comes in will have a thorough understanding of every Necromorph.

**Comment by MisterGrimm** [comment]
Help menu is not needed, as mousing over your abilities give a description of what it does. Hotkeys are already in, they are just left unbound by default due to a large amount of controversy and inability to come to a general conclusion.

If someone wishes to use hotkeys then they need to set it up on their client side in the hotkey section of options.
